clusters:                                   # a list of clusters you want to monitor
  - name: nebula                            # the cluster name
    newVersion: true                        # default false
    instances:                              # a list of instances for this cluster
      - name: metad0                        # the instance name
        endpointIP: 192.168.10.131          # the ip of this instance
        endpointPort: 19559                 # the port of this instance
        componentType: storage                # the component type of this instance, optional value metad, graphd and storaged.
extraLabels:
  - name: subsystem_name
    value: KNOWING-VIEWER
  - name: subsystem_id
    value: 5163